version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
            - ./data/certbot/dhparam:/etc/nginx/dhparam
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/logs:/var/log/letsencrypt
        networks:
            - app-network
        depends_on:
            - app

    certbot:
        image: certbot/certbot:latest
        container_name: app-certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/logs:/var/log/letsencrypt
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        networks:
            - app-network
    
    app:
        volumes:
            - /app/node_modules
        environment:
            - NODE_ENV=production
        command: yarn start
        