version: "3"
services:
    redis:
        image: redis:alpine
        container_name: app-redis
        networks:
            - app-network
        volumes:
            - ./data/redis:/data
        ports:
            - ${REDIS_PORT}:6379
        restart: unless-stopped

    mariadb:
        image: mariadb:10.3
        container_name: app-mariadb
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        networks:
            - app-network
        restart: unless-stopped

    app:
        build: .
        container_name: app
        depends_on:
            - redis
            - mariadb
        networks:
            - app-network
        command: yarn dev

networks:
    app-network:
        driver: bridge
              