version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - app-network
        depends_on:
            - app
            
    app:
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: yarn dev